# Generated by Django 2.0.6 on 2018-06-12 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Biglietto')),
                ('validitaGiorni', models.SmallIntegerField(verbose_name='Giorni di validità')),
                ('costo', models.DecimalField(decimal_places=2, default=1.5, max_digits=5, verbose_name='Costo Biglietto')),
                ('tipologia', models.CharField(choices=[('1', 'Abbonamento Mensile'), ('2', 'Corsa singola 90 minuti'), ('3', 'Biglietto 12 Corse'), ('4', 'Corsa singola integrata 120 minuti'), ('5', 'Abbonamento annuale')], max_length=50, verbose_name='Tipo Biglietto')),
            ],
        ),
        migrations.CreateModel(
            name='CartaDiCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, verbose_name='Numero Carta di Credito')),
                ('mese_scadenza', models.SmallIntegerField(verbose_name='Mese di Scadenza')),
                ('anno_scadenza', models.SmallIntegerField(verbose_name='Anno di Scadenza')),
                ('cvv', models.CharField(max_length=3, verbose_name='Codice CVV')),
            ],
        ),
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Acquisto')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Totale Transazione')),
                ('tipo_biglietto', models.CharField(choices=[('1', 'Abbonamento Mensile'), ('2', 'Corsa singola 90 minuti'), ('3', 'Biglietto 12 Corse'), ('4', 'Corsa singola integrata 120 minuti'), ('5', 'Abbonamento annuale')], max_length=50, verbose_name='Tipo Biglietto')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('cartaCredito', models.ForeignKey(on_delete='Carta di Credito', to='IswBus.CartaDiCredito')),
            ],
        ),
    ]
