# Generated by Django 2.0.6 on 2018-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IswBus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biglietto',
            name='tipologia',
            field=models.CharField(choices=[('1', 'Abbonamento Mensile'), ('2', 'Corsa singola 90 minuti'), ('3', 'Biglietto 12 Corse'), ('4', 'Corsa singola integrata 120 minuti'), ('5', 'Abbonamento annuale')], max_length=2, verbose_name='Tipo Biglietto'),
        ),
        migrations.AlterField(
            model_name='transazione',
            name='tipo_biglietto',
            field=models.CharField(choices=[('1', 'Abbonamento Mensile'), ('2', 'Corsa singola 90 minuti'), ('3', 'Biglietto 12 Corse'), ('4', 'Corsa singola integrata 120 minuti'), ('5', 'Abbonamento annuale')], max_length=2, verbose_name='Tipo Biglietto'),
        ),
    ]
