# Generated by Django 2.0.6 on 2018-06-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IswBus', '0002_auto_20180612_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='cartaCredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='IswBus.CartaDiCredito'),
        ),
    ]
