# Generated by Django 2.0.6 on 2018-06-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IswBus', '0003_auto_20180613_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transazione',
            name='tipo_biglietto',
        ),
        migrations.AddField(
            model_name='transazione',
            name='biglietto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='IswBus.Biglietto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='cognome',
            field=models.CharField(default=1, max_length=50, verbose_name='Cognome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utente',
            name='nome',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
